name: Build & One-Deploy to Azure

permissions:
  contents: read
  id-token: write

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Check out your code
      - uses: actions/checkout@v3

      # 2️⃣ Authenticate to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id:       ${{ secrets.AZUREAPPSERVICE_CLIENTID_E5978DC6004B4BB995ACD60ADAF513EF }}
          tenant-id:       ${{ secrets.AZUREAPPSERVICE_TENANTID_8824E98435E440FAA46E146AD7716A44 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6A3ECC57385541ACB3AC40EA396FC5B5 }}

      # 3️⃣ Use Node 20 and build
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

      # 4️⃣ Deploy with Azure CLI’s ZIP-push (OneDeploy under the hood)
      - name: Deploy via Azure CLI
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az webapp deploy \
              --resource-group myPortfolioRG \
              --name pubsite \
              --src-path "${{ github.workspace }}" \
              --type zip
